### ISSUE TITLE
Error: s.headers.get is not a function

### ISSUE THREAD

**Issue by Exallotriote** [kckarnige/server-scroll#2]
![image](https://github.com/kckarnige/server-scroll/assets/86817349/377c8468-71e8-4d36-a2fc-816db8f1961f)

This error keeps popping up when I try linking the script. I've tried using both raw.githubusercontent.com and the raw.githack.com to import the css files, yet it doesn't work. I'm using Vencord Web userscript.

**Comment by kckarnige** [comment]
You're importing the wrong file, you should be importing the BetterDiscord theme `(serverlistscroll.theme.css)` file, sorry for not being clearer! I'll make sure to add it to the readme :3

**Comment by Exallotriote** [comment]
My bad for opening this.

**Comment by Exallotriote** [comment]
My bad for opening this then. Should I close this issue?

**Comment by Exallotriote** [comment]
It's still not working though. I used the link you added to readme.md.

![image](https://github.com/kckarnige/server-scroll/assets/86817349/577fffdc-77f2-4e19-8661-b677eaadb509)

**Comment by kckarnige** [comment]
It seems it might be a problem with the Vencord Userscript then, try using the extension instead?
